routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('movie', 'MovieController');
Route::get('movie/destroy/{id}' , ['as' => 'movie/destroy' , 'uses' => 'MovieController@destroy']);
Route::post('movie/show' , ['as' => 'movie/show' , 'uses' => 'MovieController@show']);
Route::post('movie/update/{id}' , ['as' => 'movie/update' , 'uses' => 'MovieController@update']);
Route::get('movie/edit/{id}' , ['as' => 'movie.edit' , 'uses' => 'MovieController@update']);

//Categories

Route::resource('categories', 'CategoriesController');
Route::get('categories/destroy/{id}' , ['as' => 'categories/destroy' , 'uses' => 'CategoriesController@destroy']);
Route::post('categories/show' , ['as' => 'categories/show' , 'uses' => 'CategoriesController@show']);
Route::post('categories/update/{id}' , ['as' => 'categories/update' , 'uses' => 'CategoriesController@update']);
Route::get('categories/edit/{id}' , ['as' => 'categories.edit' , 'uses' => 'CategoriesController@update']);

//Rental

Route::resource('rental', 'RentalController');
Route::get('rental/destroy/{id}' , ['as' => 'rental/destroy' , 'uses' => 'RentalController@destroy']);
Route::post('rental/show' , ['as' => 'rental/show' , 'uses' => 'RentalController@show']);
Route::post('rental/update/{id}' , ['as' => 'rental/update' , 'uses' => 'RentalController@update']);
Route::get('rental/edit/{id}' , ['as' => 'rental.edit' , 'uses' => 'RentalController@update']);

//Roles

Route::resource('roles', 'RolesController');
Route::get('roles/destroy/{id}' , ['as' => 'roles/destroy' , 'uses' => 'RolesController@destroy']);
Route::post('roles/show' , ['as' => 'roles/show' , 'uses' => 'RolesController@show']);
Route::post('roles/update/{id}' , ['as' => 'roles/update' , 'uses' => 'RolesController@update']);
Route::get('roles/edit/{id}' , ['as' => 'roles.edit' , 'uses' => 'RolesController@update']);

//Status

Route::resource('status', 'StatusController');
Route::get('status/destroy/{id}' , ['as' => 'status/destroy' , 'uses' => 'StatusController@destroy']);
Route::post('status/show' , ['as' => 'status/show' , 'uses' => 'StatusController@show']);
Route::post('status/update/{id}' , ['as' => 'status/update' , 'uses' => 'StatusController@update']);
Route::get('status/edit/{id}' , ['as' => 'status.edit' , 'uses' => 'StatusController@update']);

//TypeStatus

Route::resource('typestatus', 'TypeStatusesController');
Route::get('typestatus/destroy/{id}' , ['as' => 'typestatus/destroy' , 'uses' => 'TypeStatusesController@destroy']);
Route::post('typestatus/show' , ['as' => 'typestatus/show' , 'uses' => 'TypeStatusesController@show']);
Route::post('typestatus/update/{id}' , ['as' => 'typestatus/update' , 'uses' => 'TypeStatusesController@update']);
Route::get('typestatus/edit/{id}' , ['as' => 'typestatus.edit' , 'uses' => 'TypeStatusesController@update']);

//users

Route::resource('users', 'UsersController');
Route::get('users/destroy/{id}' , ['as' => 'users/destroy' , 'uses' => 'UsersController@destroy']);
Route::post('users/show' , ['as' => 'users/show' , 'uses' => 'UsersController@show']);
Route::post('users/update/{id}' , ['as' => 'users/update' , 'uses' => 'UsersController@update']);
Route::get('users/edit/{id}' , ['as' => 'users.edit' , 'uses' => 'UsersController@update']);

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','status_id','role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User as User;

class UsersController extends Controller
{
    public function index()
    {
        $User = User::all();
        return view("users.list")->with("users",$User);
        //return \View::make('movies/list',compact('movies'));
    }

    public function update($id, Request $request)
    {
        $User = User::find($id);
        $User->name=$request->name;
        $User->email=$request->email;
        $User->password=$request->passwors;
        $User->status_id=$request->status_id;
        $User->role_id=$request->role_id;
        $User->save();
        return redirect('users');
    }

    public function edit($id)
    {
        $User = User::find($id);
        return view("users.update")->with("users",$User);
    }

    public function show (Request $request)
    {
        $User = User::where('name','like','%'.$request->name.'%')->get();
        return view("users.list")->with("users",$User);
    }

    public function destroy($id)
    {
        $User = User::find($id);
        $User->delete();
        return redirect()->back();
    }

    public function create()
    {
        $User = User::all();
        return view("users.new")->with("users",$User);
        //return \View::make('movies/new',compact('movies'));
    }

    public function store (Request $request)
    {
        $User = new User;
        $User->create($request->all());
        return redirect('users');
    }
}

resources/views/users/list.blade.php
@extends('layouts.app')
@section('content')
    <section class="container">
        <div class="row">
            <article class="col-md-12">
                <form action="{{route('users/show')}}" method="POST" novalidate class="form-inline">
                @csrf
                    <div class="form-group">
                        <Label>Nombre</Label>
                        <input type="text" name="name" class="form-control" namme="name">
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Buscar</button>
                        <a href="{{route('users.index')}}" class="btn btn-primary">Todo</a>
                        <a href="{{route('users.create')}}" class="btn btn-primary">Crear</a>
                    </div>
                </form>
            </article>
            <article class="col-md-12">
                <table class="table table-condensed table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th>password</th>
                            <th>Status id</th>
                            <th>Rol id</th>
                            <th>Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $users)
                        <tr>
                            <td>{{$users->name}}</td>
                            <td>{{$users->email}}</td>
                            <td>{{$users->password}}</td>
                            <td>{{$users->status_id}}</td>
                            <td>{{$users->role_id}}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="{{route('users.edit', ['id' => $users->id])}}" >Editar</a>
                                <a class="btn btn-danger btn-xs" href="{{route('users/destroy', ['id' => $users->id])}}" >Eliminar</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </article>
        </div>
    </section>
@endsection

resources/views/users/new.blade.php
@extends('layouts.app')
@section('content')
    <section class="container">
        <div class="row">
            <article class="col-md-10 col-md-offset-1">
                <form action="{{route('users.store')}}" method="post" novalidate>
                @csrf
                    <div class="form-group">
                        <label>Nombre</label>
                        <input type="text" name="name" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" name="email" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Status Id</label>
                        <input type="text" name="status_id" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Rol Id</label>
                        <input type="text" name="role_id" class="form-control" required>
                    </div>

                    <div>
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </div>
                </form>
            </article>
        </div>
    </section>
@endsection

resources/views/users/update.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <section class="container">
        <div class="row">
            <article class="col-md-10 col-md-offset-1">
                    <div class="form-group">
                            <a href="\User" class="btn btn-primary">Regresar</a>
                    </div>
                <form action='{{ url("User/update/$movie->id") }}' method="post">
                @csrf
                    <div class="form-group">
                        <h1>Actualizar Usuario</h1>
                        <label>Nombre</label>
                        <input type="text" name="name" class="form-control" required value="{{$user->name}}">
                    </div>
                    
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" name="description" class="form-control" required value="{{$user->email}}">
                    </div>

                    <div class="form-group">
                        <label>Password</label>
                        <input type="text" name="description" class="form-control" required value="{{$user->password}}">
                    </div>

                    <div class="form-group">
                        <label>Status Id</label>
                        <input type="text" name="description" class="form-control" required value="{{$user->status_id}}">
                    </div>

                    <div class="form-group">
                        <label>Rol Id</label>
                        <input type="text" name="description" class="form-control" required value="{{$user->role_id}}">
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </div>
                </form>
            </article>
        </div>
    </section>    
@endsection