routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('movie', 'MovieController');
Route::get('movie/destroy/{id}' , ['as' => 'movie/destroy' , 'uses' => 'MovieController@destroy']);
Route::post('movie/show' , ['as' => 'movie/show' , 'uses' => 'MovieController@show']);
Route::post('movie/update/{id}' , ['as' => 'movie/update' , 'uses' => 'MovieController@update']);
Route::get('movie/edit/{id}' , ['as' => 'movie.edit' , 'uses' => 'MovieController@update']);

//Categories

Route::resource('categories', 'CategoriesController');
Route::get('categories/destroy/{id}' , ['as' => 'categories/destroy' , 'uses' => 'CategoriesController@destroy']);
Route::post('categories/show' , ['as' => 'categories/show' , 'uses' => 'CategoriesController@show']);
Route::post('categories/update/{id}' , ['as' => 'categories/update' , 'uses' => 'CategoriesController@update']);
Route::get('categories/edit/{id}' , ['as' => 'categories.edit' , 'uses' => 'CategoriesController@update']);

//Rental

Route::resource('rental', 'RentalController');
Route::get('rental/destroy/{id}' , ['as' => 'rental/destroy' , 'uses' => 'RentalController@destroy']);
Route::post('rental/show' , ['as' => 'rental/show' , 'uses' => 'RentalController@show']);
Route::post('rental/update/{id}' , ['as' => 'rental/update' , 'uses' => 'RentalController@update']);
Route::get('rental/edit/{id}' , ['as' => 'rental.edit' , 'uses' => 'RentalController@update']);

//Roles

Route::resource('roles', 'RolesController');
Route::get('roles/destroy/{id}' , ['as' => 'roles/destroy' , 'uses' => 'RolesController@destroy']);
Route::post('roles/show' , ['as' => 'roles/show' , 'uses' => 'RolesController@show']);
Route::post('roles/update/{id}' , ['as' => 'roles/update' , 'uses' => 'RolesController@update']);
Route::get('roles/edit/{id}' , ['as' => 'roles.edit' , 'uses' => 'RolesController@update']);

//Status

Route::resource('status', 'StatusController');
Route::get('status/destroy/{id}' , ['as' => 'status/destroy' , 'uses' => 'StatusController@destroy']);
Route::post('status/show' , ['as' => 'status/show' , 'uses' => 'StatusController@show']);
Route::post('status/update/{id}' , ['as' => 'status/update' , 'uses' => 'StatusController@update']);
Route::get('status/edit/{id}' , ['as' => 'status.edit' , 'uses' => 'StatusController@update']);

//TypeStatus

Route::resource('typestatus', 'TypeStatusesController');
Route::get('typestatus/destroy/{id}' , ['as' => 'typestatus/destroy' , 'uses' => 'TypeStatusesController@destroy']);
Route::post('typestatus/show' , ['as' => 'typestatus/show' , 'uses' => 'TypeStatusesController@show']);
Route::post('typestatus/update/{id}' , ['as' => 'typestatus/update' , 'uses' => 'TypeStatusesController@update']);
Route::get('typestatus/edit/{id}' , ['as' => 'typestatus.edit' , 'uses' => 'TypeStatusesController@update']);

//users

Route::resource('users', 'UsersController');
Route::get('users/destroy/{id}' , ['as' => 'users/destroy' , 'uses' => 'UsersController@destroy']);
Route::post('users/show' , ['as' => 'users/show' , 'uses' => 'UsersController@show']);
Route::post('users/update/{id}' , ['as' => 'users/update' , 'uses' => 'UsersController@update']);
Route::get('users/edit/{id}' , ['as' => 'users.edit' , 'uses' => 'UsersController@update']);

app/Models/roles.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class roles extends Model
{
    protected $table = 'roles';
    protected $fillable = ['name','status_id'];
    protected $guarded = ['id'];
}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\roles as roles;

class RolesController extends Controller
{
    public function index()
    {
        $roles = roles::all();
        return view("roles.list")->with("roles",$roles);
    }

    public function update($id, Request $request)
    {
        $roles = roles::find($id);
        $roles->name=$request->name;
        $roles->status_id=$request->status_id;
        $roles->save();
        return redirect('roles');
    }

    public function edit($id)
    {
        $roles = roles::find($id);
        return view("roles.update")->with("roles",$roles);
    }

    public function show (Request $request)
    {
        $roles = roles::where('name','like','%'.$request->name.'%')->get();
        return view("roles.list")->with("roles",$roles);
    }

    public function destroy($id)
    {
        $roles = roles::find($id);
        $roles->delete();
        return redirect()->back();
    }

    public function create()
    {
        $roles = roles::all();
        return view("roles.new")->with("roles",$roles);
        //return \View::make('movies/new',compact('movies'));
    }

    public function store (Request $request)
    {
        $roles = new roles;
        $roles->create($request->all());
        return redirect('roles');
    }
}

resources/views/roles/list.blade.php
@extends('layouts.app')
@section('content')
    <section class="container">
        <div class="row">
            <article class="col-md-12">
                <form action="{{route('roles/show')}}" method="POST" novalidate class="form-inline">
                @csrf
                    <div class="form-group">
                        <Label>Nombre</Label>
                        <input type="text" name="name" class="form-control" namme="name">
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Buscar</button>
                        <a href="{{route('roles.index')}}" class="btn btn-primary">Todo</a>
                        <a href="{{route('roles.create')}}" class="btn btn-primary">Crear</a>
                    </div>
                </form>
            </article>
            <article class="col-md-12">
                <table class="table table-condensed table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Status id</th>
                            <th>Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($roles as $roles)
                        <tr>
                            <td>{{$roles->name}}</td>
                            <td>{{$roles->status_id}}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="{{route('roles.edit', ['id' => $roles->id])}}" >Editar</a>
                                <a class="btn btn-danger btn-xs" href="{{route('roles/destroy', ['id' => $roles->id])}}" >Eliminar</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </article>
        </div>
    </section>
@endsection

resources/views/roles/new.blade.php
@extends('layouts.app')
@section('content')
    <section class="container">
        <div class="row">
            <article class="col-md-10 col-md-offset-1">
                <form action="{{route('roles.store')}}" method="post" novalidate>
                @csrf
                    <div class="form-group">
                        <label>Nombre</label>
                        <input type="text" name="name" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>status id</label>
                        <input type="text" name="status_id" class="form-control" required>
                    </div>

                    <div>
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </div>
                </form>
            </article>
        </div>
    </section>
@endsection

resources/views/roles/update.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <section class="container">
        <div class="row">
            <article class="col-md-10 col-md-offset-1">
                    <div class="form-group">
                            <a href="\roles" class="btn btn-primary">Regresar</a>
                    </div>
                <form action='{{ url("roles/update/$roles->id") }}' method="post">
                @csrf
                    <div class="form-group">
                        <h1>Actualizar rol</h1>
                        <label>Nombre</label>
                        <input type="text" name="name" class="form-control" required value="{{$roles->name}}">
                    </div>
                    <div class="form-group">
                        <label>Status Id</label>
                        <input type="text" name="status_id" class="form-control" required value="{{$roles->status_id}}">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </div>
                </form>
            </article>
        </div>
    </section>    
@endsection